package com.example.logicore.core.security

enum class Permission {

    VIEW_ORDERS,
    CREATE_ORDERS,
    UPDATE_ORDERS,
    DELETE_ORDERS,

    VIEW_CUSTOMERS,
    CREATE_CUSTOMERS,
    UPDATE_CUSTOMERS,
    DELETE_CUSTOMERS,

    VIEW_VEHICLES,
    CREATE_VEHICLES,
    UPDATE_VEHICLES,
    DELETE_VEHICLES,

    VIEW_DRIVERS,
    CREATE_DRIVERS,
    UPDATE_DRIVERS,
    DELETE_DRIVERS,

    VIEW_DISPATCH,
    EXECUTE_DISPATCH,

    VIEW_WAREHOUSE,
    EXECUTE_PICKING,
    EXECUTE_LOADING,

    VIEW_REPORTS,

    MANAGE_USERS,

    MANAGE_ROLES,

    SYSTEM_ADMIN
}